/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as queueMockSol from "./QueueMock.sol";
export { QueueConsumer__factory } from "./QueueConsumer__factory";
