/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressQueueMock } from "./AddressQueueMock";
export type { Bytes32QueueMock } from "./Bytes32QueueMock";
export type { Uint256QueueMock } from "./Uint256QueueMock";
