/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as queueMockSol from "./QueueMock.sol";
export type { queueMockSol };
export type { QueueConsumer } from "./QueueConsumer";
export * as factories from "./factories";
export { QueueConsumer__factory } from "./factories/QueueConsumer__factory";
export type { AddressQueueMock } from "./QueueMock.sol/AddressQueueMock";
export { AddressQueueMock__factory } from "./factories/QueueMock.sol/AddressQueueMock__factory";
export type { Bytes32QueueMock } from "./QueueMock.sol/Bytes32QueueMock";
export { Bytes32QueueMock__factory } from "./factories/QueueMock.sol/Bytes32QueueMock__factory";
export type { Uint256QueueMock } from "./QueueMock.sol/Uint256QueueMock";
export { Uint256QueueMock__factory } from "./factories/QueueMock.sol/Uint256QueueMock__factory";
